### ISSUE TITLE
Fragment target hidden under menu bar

### ISSUE THREAD

**Issue by peterbrightwell** [AMWA-TV/nmos-doc-layouts#2]
e.g. for https://amwa-tv.github.io/nmos/branches/master/NMOS_Technical_Overview.html#general-principles, "General Principles" is under the menu bar.

**Comment by garethsb-sony** [comment]
Reminded of this again - https://github.com/AMWA-TV/nmos-testing/pull/559#pullrequestreview-475497901

**Comment by peterbrightwell** [comment]
I've gone with the scroll-padding-top approach (1150ac3fb1562ddf2187e39387b70d75f913fcbc). @garethsb-sony this works a little better than the version you saw earlier as it doesn't insert space within the page. On Android, you'll see text above the target where the menu should be but I thinkk that's fine).

See e.g. https://amwa-tv.github.io/nmos-audio-channel-mapping/tags/v1.0.1/docs/1.0._Overview.html. Others will build on cron.

**Comment by garethsb-sony** [comment]
Yes, that's great, Peter, thank you!!
